apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-vaultk8s-job
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-vaultk8s-job
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/bevel-vault-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-local
      namespace: flux-local
  values:
    nameOverride: carrier-vaultk8s-job
    global:
      serviceAccountName: vault-auth
      cluster:
        cloudNativeServices: false
        kubernetesUrl: https://34.118.88.109
      vault:
        type: hashicorp
        role: vault-role
        address: http://212.227.26.226:8200
        authPath: localcarrier
        network: fabric
        secretEngine: carrier
        secretPrefix: "data/carrier"
        tls:
    image:
      repository: ghcr.io/hyperledger/bevel-alpine
      tag: latest
      pullSecret: "regcred"
