apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-cacerts-job
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-cacerts-gen
  values:
    metadata:
      name: supplychain
      component_name: supplychain-net
      namespace: supplychain-net    
      images:
       alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    vault:
      role: vault-role
      address: http://212.227.26.226:8200
      authpath: localsupplychain
      secretcryptoprefix: secretsv2/data/supplychain/ordererOrganizations/supplychain-net/ca
      secretcredentialsprefix: secretsv2/data/supplychain/credentials/supplychain-net/ca/supplychain
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.supplychain-net
